-- test xfail
test.xfail()

fail("this is an expected failure")
