testinfo:
    summary: 'Test that Lets the Call File Fail Once Then is Answered'
    description: |
        'This test originates a Local channel through a call file that
         fails one time around, yet before the max retries are reached
         the Local channel is answered. This was confirmed through a
         UserEvent that tells whether or not the call file was actually
         executed.'

test-modules:
    add-test-to-search-path: 'True'
    test-object:
        config-section: test-object-config
        typename: 'test_case.TestCaseModule'
    modules:
        -
            config-section: hangup-config
            typename: 'pluggable_modules.HangupMonitor'
        -
            config-section: ami-config
            typename: 'ami.AMIEventModule'
        -
            config-section: call-files-config
            typename: 'pluggable_modules.CallFiles'

test-object-config:
    asterisk-instances: 1
    connect-ami: True

call-files-config:
    -
        ignore-originate-failure: 'no'
        id: '0'
        call-file-params:
            Channel: 'Local/retry_1@test_retry'
            Context: 'test_set'
            Extension: 'end'
            Priority: 1
            MaxRetries: 10
            RetryTime: 3
            WaitTime: 1

ami-config:
    -
        type: 'headermatch'
        conditions:
            match:
                Event: 'UserEvent'
                Result: 'success'
        count: '1'

hangup-config:
    ids: [ '0', ]
    min_calls: 4

properties:
    minversion: '1.8.0.0'
    dependencies:
        - python : 'twisted'
        - python : 'starpy'
        - asterisk : 'app_userevent'
        - asterisk : 'pbx_spool'
